---
- hosts: all
  user: root
  tasks:
    - name: Package manager update
      apt: update_cache=yes

    - name: Locales | en_US
      command: locale-gen en_US en_US.UTF-8
    - name: Locales | fr_BE
      command: locale-gen fr_BE fr_BE.UTF-8
    - name: Locales | reconfigure
      command: dpkg-reconfigure locales

    - name: MongoDB | Install ppa key
      apt_key: id=7F0CEB10 url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x9ECBEC467F0CEB10 state=present
    - name: MongoDB | Install ppa
      apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
    - name: MongoDB | Install package
      apt: name=mongodb-10gen state=latest
    - name: MongoDB | Install pymongo package
      apt: name=python-pip state=latest
    - pip: name=pymongo state=present
    - mongodb_user: database=admin name=admin password=admin roles='userAdmin'
    - name: MongoDB | Import banks data
      command: mongoimport -d chech-lajan -c banks --file /vagrant/_dev/banks.json
    - name: MongoDB | Import terminals data
      command: mongoimport -d chech-lajan -c terminals --file /vagrant/_dev/terminals.json

    - name: node.js | Install ppa key
      apt_key: id=C7917B12 url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xB9316A7BC7917B12 state=present
    - name: node.js | Install ppa
      apt_repository: repo=ppa:chris-lea/node.js state=present
    - name: node.js | Install package
      apt: name=nodejs state=latest
    - npm: name=grunt-cli global=yes
    - npm: path=/vagrant
    - name: nginx | Install package
      apt: name=nginx-extras state=latest
    - copy: src="nginx.conf" dest="/etc/nginx.conf"
    - copy: src="default-host.conf" dest="/etc/nginx/sites-available/default"
    - name: nginx | Check service daemon
      service: name=nginx state=started
